version: '3.8'
services:
  airflow-db:
    image: postgres:13
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5
      start_period: 30s

  airflow-webserver:
    image: apache/airflow:2.6.2-python3.10
    container_name: airflow-webserver
    entrypoint: /bin/bash -c "airflow db reset --yes && airflow db init && airflow users create --username vini --password admin --firstname Vini --lastname Otoni --email viniciusotonimvs@gmail.com --role Admin && pip install -r /opt/airflow/requirements.txt && airflow webserver"
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - PYTHONPATH=/opt/airflow/ETL
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./ETL/bronze:/opt/airflow/ETL/bronze
      - ./airflow/requirements.txt:/opt/airflow/requirements.txt
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 45s
      retries: 2

  airflow-scheduler:
    image: apache/airflow:2.6.2-python3.10
    container_name: airflow-scheduler
    entrypoint: ["airflow", "scheduler"]
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./ETL/bronze:/opt/airflow/ETL/bronze
      - ./airflow/requirements.txt:/opt/airflow/requirements.txt
    depends_on:
      airflow-webserver:
        condition: service_healthy
      airflow-db:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow

volumes:
  postgres-data:
    driver: local
